//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CCP.rc
//
#define IDD_CCP_DIALOG                  102
#define IDD_PAGE_NUMBER                 103
#define IDD_PAGE_ROUTE                  105
#define IDD_PAGE_CONFIG                 106
#define IDD_PAGE_HELP                   108
#define IDD_PAGE_PEI                    109
#define IDD_PAGE_MESSAGE                110
#define IDD_PAGE_PR                     111
#define IDD_PAGE_CI                     112
#define IDR_MAINFRAME                   128
#define IDS_BUILDDATE                   144
#define IDC_BTN_HOME                    1001
#define IDC_BTN_TRAIN                   1002
#define IDC_BTN_CREW                    1003
#define IDC_BTN_ROUTE                   1004
#define IDC_BTN_CONFIG                  1005
#define IDC_BTN_CHECK                   1006
#define IDC_BTN_HELP                    1007
#define IDC_BTN_PEI                     1008
#define IDC_BTN_MESSAGE                 1009
#define IDC_TIME_LABEL                  1010
#define IDC_BTN_CM                      1010
#define IDC_LAST_STATION                1011
#define IDC_BTN_SPK_INT_SOFT            1011
#define IDC_LAST_TIME                   1012
#define IDC_BTN_SPK_INT_NORMAL          1012
#define IDC_LAST_DELAY                  1013
#define IDC_BTN_SPK_EXT_SOFT            1013
#define IDC_ROUTE                       1014
#define IDC_BTN_SPK_EXT_NORMAL          1014
#define IDC_STATE_GPS                   1015
#define IDC_BTN_SPK_EXT_MUTE            1015
#define IDC_STATE_LIC                   1016
#define IDC_BTN_LIGHT_DOWN              1016
#define IDC_STATE_CNCS                  1017
#define IDC_BTN_LIGHT_UP                1017
#define IDC_STATE_LEDPIS                1018
#define IDC_LIGHT                       1018
#define IDC_STATE_ESPK                  1019
#define IDC_BTN_RESET_OK                1019
#define IDC_STATE_CONKEY                1020
#define IDC_BTN_RESET_CANCEL            1020
#define IDC_STATE_REVERSE               1021
#define IDC_BTN_SIMULATION_10           1021
#define IDC_STATE_DOORL                 1022
#define IDC_BTN_SIMULATION_20           1022
#define IDC_STATE_WLAN                  1023
#define IDC_BTN_SIMULATION_30           1023
#define IDC_STATE_PAC                   1024
#define IDC_BTN_SPK_CAB_SOFT            1024
#define IDC_STATE_VTX                   1025
#define IDC_BTN_SPK_CAB_NORMAL          1025
#define IDC_STATE_LCDPIS                1026
#define IDC_STATE_CABKEY                1027
#define IDC_STATE_FORWORD               1028
#define IDC_STATE_DOORR                 1029
#define IDC_DEPARTURE_NAME              1030
#define IDC_DEPARTURE_TIME              1031
#define IDC_LAST_STATION4               1032
#define IDC_DEPARTURE_DELAY             1032
#define IDC_ACTUAL_NAME                 1033
#define IDC_ACTUAL_TIME                 1034
#define IDC_ACTUAL_DELAY                1035
#define IDC_NEXT_NAME                   1036
#define IDC_NEXT_TIME                   1037
#define IDC_ACTUAL_DELAY2               1038
#define IDC_NEXT_DELAY                  1038
#define IDC_RADIO1                      1040
#define IDC_BTN_                        1041
#define IDC_BTN_SIMULATION              1041
#define IDC_BTN_NO1                     1042
#define IDC_BTN_NO2                     1043
#define IDC_BTN_NO3                     1044
#define IDC_BTN_NO4                     1045
#define IDC_BTN_NO5                     1046
#define IDC_BTN_NO6                     1047
#define IDC_ACTIVATE_ONE                1048
#define IDC_BTN_NO7                     1048
#define IDC_ACTIVATE_TWO                1049
#define IDC_BTN_NO8                     1049
#define IDC_STATIC_TEXT                 1050
#define IDC_ACTIVATE_THREE              1050
#define IDC_BTN_NO9                     1050
#define IDC_ACTIVATE_FOUR               1051
#define IDC_BTN_AUTO                    1051
#define IDC_ACTIVATE_FIVE               1052
#define IDC_BTN_NO10                    1052
#define IDC_BTN_APPLY                   1052
#define IDC_ACTIVATE_SIX                1053
#define IDC_BUTTON_1                    1351
#define IDC_BUTTON_2                    1352
#define IDC_BUTTON_3                    1353
#define IDC_BUTTON_4                    1354
#define IDC_BUTTON_5                    1355
#define IDC_BUTTON_6                    1356
#define IDC_BUTTON_7                    1357
#define IDC_BUTTON_8                    1358
#define IDC_BUTTON_9                    1359
#define IDC_BUTTON_0                    1360
#define IDC_BUTTON_CLEAR                1361
#define IDC_BUTTON_ENTER                1362
#define IDC_SCROLLBAR_ROUTE             1501
#define IDC_LIST_ONE                    1502
#define IDC_LIST_TWO                    1503
#define IDC_LIST_THREE                  1504
#define IDC_LIST_FOUR                   1505
#define IDC_LIST_FIVE                   1506
#define IDC_LIST_SIX                    1507
#define IDC_STOP_ONE                    1508
#define IDC_STOP_TWO                    1509
#define IDC_STOP_THREE                  1510
#define IDC_STOP_FOUR                   1511
#define IDC_STOP_FIVE                   1512
#define IDC_STOP_SIX                    1513
#define IDC_SKIP_ONE                    1514
#define IDC_SKIP_TWO                    1515
#define IDC_SKIP_THREE                  1516
#define IDC_SKIP_FOUR                   1517
#define IDC_SKIP_FIVE                   1518
#define IDC_SKIP_SIX                    1519
#define IDC_EXP_ONE                     1520
#define IDC_EXP_TWO                     1521
#define IDC_EXP_THREE                   1522
#define IDC_EXP_FOUR                    1523
#define IDC_EXP_FIVE                    1524
#define IDC_EXP_SIX                     1525
#define IDC_LOCAL_ONE                   1526
#define IDC_LOCAL_TWO                   1527
#define IDC_LOCAL_THREE                 1528
#define IDC_LOCAL_FOUR                  1529
#define IDC_LOCAL_FIVE                  1530
#define IDC_LOCAL_SIX                   1531
#define IDC_BUTTON_SPEAKER              1601
#define IDC_BUTTON_LCD                  1602
#define IDC_BUTTON_RESET                1603
#define IDC_BUTTON_TOUCH                1604
#define IDC_BUTTON_SIMULATION           1605
#define IDC_BUTTON_SPARE6               1606
#define IDC_APP_VERSION                 1809
#define IDC_HELP_TITLE                  1810
#define IDC_HELP_EDIT                   1811
#define IDC_BTN_CAR1                    1901
#define IDC_BTN_CAR2                    1902
#define IDC_BTN_CAR3                    1903
#define IDC_BTN_CAR4                    1904
#define IDC_BTN_CAR5                    1905
#define IDC_BTN_CAR6                    1906
#define IDC_BTN_CAR7                    1907
#define IDC_BTN_CAR8                    1908
#define IDC_BTN_CAR9                    1909
#define IDC_BTN_CAR10                   1910
#define IDC_BTN_CAR11                   1911
#define IDC_BTN_CAR12                   1912
#define IDC_MSG_ONE                     2001
#define IDC_MSG_TWO                     2002
#define IDC_MSG_THREE                   2003
#define IDC_MSG_FOUR                    2004
#define IDC_MSG_FIVE                    2005
#define IDC_MSG_SIX                     2006
#define IDC_MSG_NUM_ONE                 2007
#define IDC_MSG_NUM_TWO                 2008
#define IDC_MSG_NUM_THREE               2009
#define IDC_MSG_NUM_FOUR                2010
#define IDC_MSG_NUM_FIVE                2011
#define IDC_MSG_NUM_SIX                 2012
#define IDC_CLEAR_ONE                   2013
#define IDC_CLEAR_TWO                   2014
#define IDC_CLEAR_THREE                 2015
#define IDC_CLEAR_FOUR                  2016
#define IDC_CLEAR_FIVE                  2017
#define IDC_CLEAR_SIX                   2018
#define IDC_REPRINT_ONE                 2019
#define IDC_REPRINT_TWO                 2020
#define IDC_REPRINT_THREE               2021
#define IDC_REPRINT_FOUR                2022
#define IDC_REPRINT_FIVE                2023
#define IDC_REPRINT_SIX                 2024
#define IDC_MSG_SCROLL                  2025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
